Repository TheTedLab/game-critic-bot, pull requests merged in 2021-12, with the labels that each got.

#34 Docker
  .github/workflows/ci.yml
  Dockerfile
  src/bot.py
  src/commands.py
  src/test/conftest.py
  src/test/test_parsing.py
Labels: enhancement

#35 Fixed bug with one page
  src/data_scraping.py
Labels: bug

#36 Create search game and platform bot conversations
  .gitattributes
  src/bot.py
  src/commands.py
  src/constants.py
  src/data_scraping.py
Labels: enhancement

#37 Function for description, number of reviews, user score
  src/data_scraping.py
Labels: enhancement

#38 Fixed bugs with url and description
  src/data_scraping.py
Labels: bug

#39 Create image parsing and description
  requirements.txt
  src/commands.py
  src/data_scraping.py
  src/images/__init__.py
  src/images/game_image.jpg
  src/images/game_metacritic_icon.jpg
  src/images/metacritic_logo.png
  src/images/no_search_results.png
  src/images/search.png
Labels: bug, enhancement

#40 Dev edition merge [Fourth Sprint]
  .gitattributes
  .github/workflows/ci.yml
  Dockerfile
  requirements.txt
  src/bot.py
  src/commands.py
  src/constants.py
  src/data_scraping.py
  src/images/__init__.py
  src/images/game_image.jpg
  src/images/game_metacritic_icon.jpg
  src/images/metacritic_logo.png
  src/images/no_search_results.png
  src/images/search.png
  src/test/conftest.py
  src/test/test_parsing.py
Labels: enhancement

#41 Add docker bot build and run
  Dockerfile
  README.md
  src/bot.py
  src/commands.py
Labels: documentation, enhancement

#42 Docker improvement
  Dockerfile
  README.md
  src/bot.py
  src/commands.py
Labels: bug, documentation, enhancement

#44 Add bot testing into Docker
  Dockerfile
  README.md
  src/docker_script.py
  src/test/conftest.py
  src/test/get_session_string.py
  src/test/test_bot.py
Labels: bug, documentation, enhancement
